# Generated by Django 3.2 on 2021-04-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_selectedproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedproject',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DENIED', 'DENIED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=300),
        ),
    ]
