# Generated by Django 3.2 on 2021-04-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_selectedproject_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DENIED', 'DENIED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=300),
        ),
    ]
