# Generated by Django 3.2 on 2021-04-21 15:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0005_rename_projectproposal_topic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SelectedProject',
            new_name='SelectedTopic',
        ),
    ]
