# Generated by Django 3.2 on 2021-04-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0007_projectproposal_proposalfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectproposal',
            name='comment',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='proposalfeedback',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proposalfeedback',
            name='feedback_file',
            field=models.FileField(blank=True, upload_to='feedback_files'),
        ),
    ]
