# Generated by Django 3.2 on 2021-04-22 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_projectsubmission_projectsubmissionfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
