# Generated by Django 3.2 on 2021-04-23 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_projectsubmission_is_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='is_submitted',
        ),
    ]
