# Generated by Django 3.2 on 2021-04-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0012_projectmaterial_projectmaterialsfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaterial',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_app.selectedtopic'),
        ),
    ]
