# Generated by Django 3.2.2 on 2021-05-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_thesis', '0002_alter_projectmaterial_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmaterial',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_thesis.selectedtopic'),
        ),
    ]
